### ISSUE TITLE
Development Function 0x10-Write Multiple Registers

### ISSUE THREAD

**Issue by sgryb** [angeloc/simplemodbusng#13]
Thank you for a great compact library.
Would you be so kind and consider developing Function 10 for multiple registers.
Thank you!

**Comment by limitedAtonement** [comment]
I think the author does not have the resources to implement that feature at this time, nor in the previous several years. Consider issuing a pull request? The library is written very clearly, and it should not be difficult to implement.

**Comment by angeloc** [comment]
@sgryb yes, please do a PR or sponsor for the feature development. Thanks!
