### ISSUE TITLE
Arduino Modbus master and raspberry pi as slave

### ISSUE THREAD

**Issue by akshulg** [angeloc/simplemodbusng#14]
@angeloc  I am trying to implement the same thing written in the title. Using pymodbus for raspberry pi. But having problem and getting some error. Serial monitor on arduino is printing random garbage values. Can anyone tell me properly how simplemodbusmsater library works and explain me example code. Is the library made to print the holding register values we get from slave device(raspberry pi)? I found serial.read and serial.write commands for frame[buffer] in .cpp file so thats how i concluded that it can print the register values on monitor. But maybe i am wrong. So please if anyone call tell me how the library actually works that would be helpful.

**Comment by limitedAtonement** [comment]
This can probably be closed. If it's still an issue, please look at the code repository for excellent example code.
