### ISSUE TITLE
Multiple Slaves

### ISSUE THREAD

**Issue by Jono72** [angeloc/simplemodbusng#17]
Hi All,

I need to read register from multiple slaves on the bus, how can I achieve this maximising processing power? I will have a maximum of 16 Slaves with no more than 10 registers in each, these will also be Coils or Discrete only as I'm monitoring/controlling digital states, Would obviously like to poll each device write and return data for all 16 Slaves on the bus.

Regards

Jono

**Comment by angeloc** [comment]
I don't understand the question, sorry. Modbus keeps the bus busy while doing operation, so you have te read the date from one node at a time.
