### ISSUE TITLE
Accessing 100 Holding registers

### ISSUE THREAD

**Issue by b4ulook4me** [angeloc/simplemodbusng#5]
Hello,
 I am trying to access 100 Holding registers, can't get past 28 registers. Not able to identify the problem.
Have tried with different levels of delay. Platform, Arduino via MAX485 ic, pin 2 as tx enable.
 baud 9600, parity even, 8 bits.
start.
a. modbus_construct 
 b. delay(100)
c. modbus_update()
 d. read registers
e. delay(25)
f. delay(1)
back to loop

**Comment by limitedAtonement** [comment]
This can probably be closed. If the issue still stands, please answer: are you able to read one register?
