### ISSUE TITLE
Feature request : Softserial for master

### ISSUE THREAD

**Issue by Memes11** [angeloc/simplemodbusng#7]
all in title, I am looking for that desperately

**Comment by angeloc** [comment]
Hi @Memes11,

How much are you willing to pay?

**Comment by Memes11** [comment]
Hi angeloc, maybe some of my time to help you test, since I am not desperate anymore, found another solution, turned out I did not need it :)

**Comment by nkl-nklc** [comment]
Hi @Memes11,

could you sare with us how you implemented software serial ?

**Comment by akshulg** [comment]
@Memes11 can you share the solution for software serial for modbus master?

**Comment by akshulg** [comment]
@Memes11 @angeloc @angeloc is it okay to read the register values from slave using the rx and tx pin of arduino and at the same time printing those values on serial monitor. I am implementing arduino as master and raspberry pi as slave but getting garbage values on serial monitor. Any idea why is this happening?

**Comment by limitedAtonement** [comment]
@akshulg I think your question has nothing to do with this issue. To answer your question, that should be fine as long as you have multiple UART modules. Perhaps you are using the same serial module for monitoring and RS-485?
